---
language: minimal

branches:
  only:
  - master

services:
- docker

env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # Do not prompt for user input when using any SDK methods.
  - DOCKER_HUB_USERNAME=miketrout
  - secure: UMxk7uNuIU3lICZJPRaW3MVIAIhryJmPFD08naF4oRk55lVqyh62vlC9q++6BrNjZ92XB+MeZrMVw1eoIMmC0NDGDa2oHRaRQIWEjfMN5Iilusybmc+96W0PiVwX3MwW25N3oxT98p0k4BLjiHXeETvuPNE6a1XqBZsuV1rDiJeX4tn3LFeet3ObvSlLBuq/IQJjxtgdUe3q2PfRxc3FoFCo1/KzKisP4Bd3iyzBBoYJGliAwQ2TnB6/SnGJa7HE7i5ue9k0PNdsLY0i+byO6Jb3xF7qPrgD9LZ31Xy5Ao1bWz10tv5J1PAa7QbKAJZlWJfpwzzkLFN+vgQP1/ehncCi+db9tlKDm8qd+TQkdoIy4oWGaEwOaAcUlDYbucV2GK9YhcTz5k0d0FcUoHw99v/5/V1OWhTPnraYJQGjsG9b1k/u1sUhi3v8kmip07siyq0x5vn2528r0p1ShaSWz/xwNL+nUn1pvGaRKm9uY1lSkX10TrdEE+eaKsY664Ters2w5jSVVeleW645paPVe4IkVCEuHvAtpH5UBuh/BHG5pkVwz0pM6V+voKouKUczLX1HjPyth2GnG8OqgPe/emONP1xz3uSjV1wDTprerp6ehdki5Tct5u4U7SR56YRP0vM2aHQzkNbhVuX3Dz+XXefL8adGCLWJ4Va9fhcVOhk=

addons:
  apt:
    packages:
    - docker-ce

before_install:
- openssl aes-256-cbc -K $encrypted_7b46ec655703_key -iv $encrypted_7b46ec655703_iv -in gcloud-service-account-secret.json.enc -out gcloud-service-account-secret.json -d

script:
- docker --version
- docker build -t miketrout/experience-service .
- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
- docker push miketrout/experience-service

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
