---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: experience-service-deployment
  labels:
    service: experience-service
    tier: backend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      service: experience-service
      tier: backend
  template:
    metadata:
      labels:
        service: experience-service
        tier: backend
    spec:
      containers:
        - name: experience-service
          image: miketrout/experience-service
          imagePullPolicy: Always
          resources:
            requests:
              memory: 15Mi
              cpu: 10m
            limits:
              memory: 25Mi
              cpu: 50m
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          env:
            - name: HTTP_PORT
              value: "50000"
          ports:
            - name: http
              containerPort: 50000
