---
apiVersion: v1
kind: Service
metadata:
  name: experience-service-service
spec:
  type: NodePort
  selector:
    service: experience-service
    tier: backend
  ports:
    - name: http
      protocol: TCP
      port: 60000
      targetPort: 50000
